language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
after_install: npm ls >/dev/null
before_script: npm run greenkeeper:update-lockfile
before_deploy:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "dsmJS Bot"
after_success: npm run semantic-release
after_script: npm run greenkeeper:upload-lockfile
env:
  global:
  - secure: Ol3EIBFbxgIAXNQ0puF5JyWPWqpAoL6AUaxABzJ1sGA5bqYZRMus+NL2uQXUp4orIqGYqcUVO8yYL8G6sUb+p99usNxmIaekzmOk3kaokdBfyZW4Md28+cUvGk8Xa7/OmMLLo9hPPPYz4hvNbuulImKP52I8lkiu9VUHYzmW8QQuEMHh6QV1ZhR5+hReXYxjydhmwUzxKRWqNBDxfT4zr0bJ03RmcE/j5fS6UockPKMuM8LyxqAL6MwaWniZY6ruHwMOnXGWyZkSWgW5Z9APSd0sm4Qdcuzs4rb6vN5SFfTEQAgEdzAzMFdMrjMWuzi/H63bXnY2/hZo+ikuZth48ycoTwtJ1RT0oMqUukpRutgcAjQSJFK67DNhWKHIDa7nnLUX5CPPhV8xyv1GUKWpYMJFbby35Smw95jeD/+mRyYl1NKNs4n598YxxtVZlRysZ9/z5uBeCTXpjE21KxlgBtu/ps4TXDO0i/WED0PxrOVJl+pDfdv0+cWPSCeJp/dZkEBWOmtDYaA1rC1FVKEpwIxjYEbio8AGPTvfXo79AxZLXF26hlXpxCBb3p8+hOeUdqBsiWPD1Orztj86zTMOl75HylKcvmwG9kysFMW8U2n/PLVmNnWfeFEpuxFw6XeFSt+tZDO66Fsn3q+/YGcXpFooGZX8jGlfCJ5izCvIvMc=
  - secure: L30ZMkFKHWiHVqaUUTHi3vS4fJuRkQ/MEtXwVDyby29F7VuAJuFWk+/cud5dmK0X3Gr7d+Bjjh3FgWGBnnHARTlvFkHGW/hi50UXQPNrVkpSs02XKZh9nmj+YkKV5yrESZjjMLSfv3BsRtgfKJG1ldw4kaa4/Bsow7kvNskClwvTAPWzw5tJ+5wh4VYhcvdKLWKye+FSQ/TDGqhz24sfEO1jZO+SgfsNr90NsGoGxwcIoYN31Iy4Tp4VI3n12A+LrA+cquujEiAXMB287yPu/WD+z9aSzQdPC7RbrrinPm8EmYEeWS0JR2eVN51JVDeLNgFVbzWm2wt7iOY9Jw1byI9d0Pak6q0m/do+su1Xg0PwPlmFWTx+exshzjmBhdBPJn11v/91947kHjAi854VyTd3MX/Qu3bvhaMvuTp/ShjWt4cdK2u/Nv6qYcCBx+jIB91enFjRXQKJWTdynGVIIznV8SyymXljVu4EqYvO6Oun7WLodYGp87LuKq/F1NvSHs5npEb6MmIomwankrLN+HlZ+T6JvzjY+d4j3OUFlIS3c1kbShdnMDYrm/9pHbyykHaZvCkQ8Y17qVo5MtXCZTWuGBrYyUn1mxd8GeJ+KQ3BfK7vbu/O7g9+LCcgqqGpohahjXiWFfXJhRx6pKEbpkJ4nEhOeBECqUmg+o4OrFY=
