language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
after_install: npm ls >/dev/null
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
before_deploy:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "dsmJS Bot"
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: Ol3EIBFbxgIAXNQ0puF5JyWPWqpAoL6AUaxABzJ1sGA5bqYZRMus+NL2uQXUp4orIqGYqcUVO8yYL8G6sUb+p99usNxmIaekzmOk3kaokdBfyZW4Md28+cUvGk8Xa7/OmMLLo9hPPPYz4hvNbuulImKP52I8lkiu9VUHYzmW8QQuEMHh6QV1ZhR5+hReXYxjydhmwUzxKRWqNBDxfT4zr0bJ03RmcE/j5fS6UockPKMuM8LyxqAL6MwaWniZY6ruHwMOnXGWyZkSWgW5Z9APSd0sm4Qdcuzs4rb6vN5SFfTEQAgEdzAzMFdMrjMWuzi/H63bXnY2/hZo+ikuZth48ycoTwtJ1RT0oMqUukpRutgcAjQSJFK67DNhWKHIDa7nnLUX5CPPhV8xyv1GUKWpYMJFbby35Smw95jeD/+mRyYl1NKNs4n598YxxtVZlRysZ9/z5uBeCTXpjE21KxlgBtu/ps4TXDO0i/WED0PxrOVJl+pDfdv0+cWPSCeJp/dZkEBWOmtDYaA1rC1FVKEpwIxjYEbio8AGPTvfXo79AxZLXF26hlXpxCBb3p8+hOeUdqBsiWPD1Orztj86zTMOl75HylKcvmwG9kysFMW8U2n/PLVmNnWfeFEpuxFw6XeFSt+tZDO66Fsn3q+/YGcXpFooGZX8jGlfCJ5izCvIvMc=
  - secure: V/wMNecmPlEP6looDo5KH/vlRXBiEiPlq4oIaaO0rLdxZqUAkESuiUzv+Y9zN5GxmZgIwD+IhA2wcbyR5Mo+Y+1lh1uuPpm8V6YCzScF1knWDb63wrPazxStHkJQL2S3Yfz8X3GiXGGe5W4H1/w7lO5C6LwFpv1jjVU4jHNXzJyPXWIZoIUgcLRntTf9kinhLlaaO1LJdSpQ0dyZOkVxX5kGiElVlPXrsLxyTmlgyfRWdHJgOCvfwgJbpqHgNmpxo+tGtyBt9ptgvu/lX/8RInIy1ldJULiVALNFPXGk9cjsQnyoTUfVup8ehr0d1jbnWMRB+Fg+Dq5nKfPOOw9a9kT2nCwUoZofn7hLrNtHyb+F52/a1GYpU61MuGDZvqOXaphnRgsUP+yH5V4xWIdJrUgtUts4YlGA5GvgDXymMXFQj4N4Ie+Dr5a6TutZlo5yT0KshGBaPrlsWRA3Bj0jlG2ilAhBn/KeqNUWPjlCNjN2vx25ylLJn0IZRLpS7d3X51+F6clIhDSfCEGI1mzxCizZrRwVk1VP2WoZQYyScrOa+KWtDBbdRNj2jYRG79yj+wVRBHaPhXIyddOsAscFpvzxTU6Lfqg77+1tJ6t/ZUdDJEZaXEhLozfNhfmFzfQNYa0OBN6M0jgOMVDIP92QUr7FStJeOhsY50UAtre8CBE=
