version: ~> 1.0
notifications:
  email: false
import:
  - source: form8ion/.travis-ci:node.yml
  - source: dsmjs/.travis-ci:authenticated-semantic-release.yml
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
after_install: npm ls >/dev/null
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
before_deploy:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "dsmJS Bot"
